name: "PR Title Check"
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload
            const prTitle = payload.pull_request.title
            const casePattern = /^\d+:\s\w.+/g
            if (!casePattern.test(prTitle)) {
              console.log('PR title should start with case number!')
              console.log('Example: "1234: implemented new feature"')
              core.setFailed('PR title has incorrect format')
            } else {
              console.log('PR title format is correct.')
            }
