name: Release notes

on:
  push:
    branches:
      - main
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    uses: ppechkurov/workflows/.github/workflows/release-notes.yml@master
